repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.8.3'
    hooks:
      - id: poetry-check
      - id: poetry-lock
      - id: poetry-export
      - id: poetry-install

  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black
        language: system
        types: [file, python]

      - id: isort
        name: isort
        entry: poetry run isort
        language: system
        types: [file, python]
