# Please refer to https://scipy.github.io/devdocs/building/index.html
# To use:
#   $ conda env create -f environment.yml  # `mamba` works too for this command
#   $ conda activate regrank-dev
#
name: regrank-dev
channels:
  - pytorch
  - conda-forge
  - gurobi
  - defaults
dependencies:
  - python=3.12
  - pre-commit
  - ax-platform
  - pytorch
  - torchvision
  - ipykernel
  - graph-tool
  - graphviz
  - python-graphviz
  - cvxpy
  - seaborn
  - bson
  - pymongo
  - scipy
  - numpy
  - numba
  - scikit-learn
  - gurobi
  - marimo>=0.8  # for tutorials
  - distinctipy
  # regrank.datasets dependency
  - pooch
  # For testing and benchmarking
  - pytest
  - scalene
  - prettytable
  # For building docs
  - sphinx
  - myst-parser
  - intersphinx-registry
  - numpydoc
  - ipython
  - setuptools<67.3  # avoid pkg_resources deprecation warnings from MPL/scikit-umfpack
  - matplotlib
  - sphinx-markdown-tables
  - sphinx_rtd_theme==2.0.0
  - recommonmark
  - numpydoc
  - mathjax
  # For CLI
  - click
  # For linting
  - ruff>=0.0.292
  - restructuredtext_lint
  - doc8
