[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[project]
name = "rSpringRank"
authors = [{ name = "Tzu-Chi Yen", email = "tzuchi.yen@colorado.edu" }]
description = "Regularized methods for efficient ranking in networks"
requires-python = ">=3.9"
keywords = [
    'network-analysis',
    'convex-optimization',
    'ranking-algorithm',
    'proximal-gradient-method',
    'denoising',
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
    'Natural Language :: English',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Scientific/Engineering',
    'Topic :: Software Development :: Libraries',
]

dynamic = ["version"]

dependencies = [ "networkx", "scipy", "cvxpy", "matplotlib", "numba", "bson", "pymongo"]

[project.optional-dependencies]
dev = ["pytest", "click", "sphinx"]

[project.urls]
repository = 'https://github.com/junipertcy/rSpringRank'
documentation = 'https://docs.netscied.tw/rSpringRank/index.html'

[project.readme]
file = "README.md"
content-type = "text/markdown"

[tool.setuptools]
packages = ["rSpringRank"]

[tool.setuptools_scm]
write_to = "rSpringRank/_version.py"

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64"]

[tool.pixi.pypi-dependencies]
rSpringRank = { path = ".", editable = true }

[tool.pixi.environments]
default = { solve-group = "default" }
dev = { features = ["dev"], solve-group = "default" }

[tool.pixi.tasks]

[tool.pixi.dependencies]
graph-tool = ">=2.68,<3"
cvxpy = ">=1.5.1,<1.6"
networkx = ">=3.3,<4"
scipy = ">=1.13.1,<1.14"
matplotlib = ">=3.8.4,<3.9"
numba = ">=0.59.1,<0.60"
bson = ">=0.5.9,<0.6"
pymongo = ">=4.7.2,<4.8"
seaborn = ">=0.13.2,<0.14"

[tool.pixi.build-dependencies]
pytest = ">=8.2.1,<8.3"
click = ">=8.1.7,<8.2"
sphinx = ">=7.3.7,<7.4"
