[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "rspringrank"
version = "0.2.0"
description = "Regularized methods for efficient ranking in networks"
authors = ["Tzu-Chi Yen <tzuchi.yen@colorado.edu>"]
license = "LGPL-3.0-or-later"
readme = "README.md"


[project]
name = "rSpringRank"
authors = [{ name = "Tzu-Chi Yen", email = "tzuchi.yen@colorado.edu" }]
description = "Regularized methods for efficient ranking in networks"
requires-python = ">=3.9"
keywords = [
    'network-analysis',
    'convex-optimization',
    'ranking-algorithm',
    'proximal-gradient-method',
    'denoising',
]
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Science/Research',
    'License :: OSI Approved :: GNU Lesser General Public License v3 (LGPLv3)',
    'Natural Language :: English',
    'Operating System :: Microsoft :: Windows',
    'Operating System :: POSIX',
    'Operating System :: Unix',
    'Operating System :: MacOS',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3 :: Only',
    'Topic :: Scientific/Engineering',
    'Topic :: Software Development :: Libraries',
]

dynamic = ["version"]

dependencies = [
    "networkx",
    "scipy",
    "cvxpy",
    "matplotlib",
    "numba",
    "bson",
    "pymongo",
]

[project.optional-dependencies]
dev = ["pytest", "click", "sphinx"]

[project.urls]
repository = 'https://github.com/junipertcy/rSpringRank'
documentation = 'https://docs.netscied.tw/rSpringRank/index.html'

[project.readme]
file = "README.md"
content-type = "text/markdown"


[tool.poetry.dependencies]
python = "^3.10"
cvxpy = "^1.5.1"

[tool.poetry.group.dev.dependencies]
Sphinx = "^7.3.7"
intersphinx-registry = "^0.2406.4"
numpydoc = "^1.7.0"
