name: Release

on:
  release:
    types:
      - created

jobs:
  release-job:
    name: Build and publish on PyPI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3.0.4
        with:
          python-version: 3.10
          environment-file: environment.yml
          auto-update-conda: true
          auto-activate-base: false
      - name: Install dependencies
        run: conda env update --file environment.yml
  
      - name: Activate environment
        run: source activate rSpringRank-dev
      
      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python3 -

      - name: Install dependencies
        run: poetry install --no-root

      - name: Build package
        run: poetry build

      - name: Check sdist install and imports
        run: |
          mkdir -p test-sdist
          cd test-sdist
          python -m venv venv-sdist
          venv-sdist/bin/python -m pip install ../dist/rspringrank-*.tar.gz
          venv-sdist/bin/python -c "import rSpringRank"

      - name: Check wheel install and imports
        run: |
          mkdir -p test-wheel
          cd test-wheel
          python -m venv venv-wheel
          venv-wheel/bin/python -m pip install ../dist/rspringrank-*.whl
          venv-wheel/bin/python -c "import rSpringRank"

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: poetry publish --build
